version: '2'
services:
    meusfilmes-mongodb:
        container_name: meusfilmes-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/MeusFilmes/mongodb/:/data/db/
